  name: push to ECR 
  
  on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]
  
  env:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: forkits-web
    AWS_ACCOUNT_ID: 428713192206
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v5.1.0
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
            aws-region: ${{ secrets.AWS_REGION}}
        
        - name: Login to Amazon ECR
          run: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 428713192206.dkr.ecr.us-east-1.amazonaws.com
  
        - name: Build, tag, and push docker image to Amazon ECR
          run: |
            IMAGE_TAG=$(date +%s)
            IMAGE_URL=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
  
            echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
            
            docker build -t $IMAGE_URL .
            docker push $IMAGE_URL
